format = '''
$directory$git_branch$git_commit$git_status$git_metrics$git_state
$os$hostname$character '''

[character]
    success_symbol = '[➜](green)'
    error_symbol = "[➜](bold red)"

[directory]
    truncate_to_repo = false
    truncation_length = 2
    truncation_symbol = '…/'
    style = 'blink italic cyan'

[hostname]
    format = '[$hostname](yellow) '
    ssh_only = false

[git_branch]
    style = "purple"

[git_status]
    format = '(\[[($ahead_behind )($all_status)]($style)\])'
    style = "purple"
    stashed = "*${count}"
    ahead = "⇡${count}"
    behind = "⇣${count}"
    up_to_date = ""
    diverged = "⇡${ahead_count}⇣${behind_count}"
    conflicted = "=${count}"
    deleted = "×${count}"
    renamed = "»${count}"
    modified = "!${count}"
    staged = "+${count}"
    untracked = "?${count}"
    ignore_submodules = false
    disabled = false